// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clinics.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClinic = `-- name: CreateClinic :one
INSERT INTO clinics (name, slug, address, phone, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at
`

type CreateClinicParams struct {
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, createClinic,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.Phone,
		arg.IsActive,
	)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
	)
	return i, err
}

const deleteClinic = `-- name: DeleteClinic :exec
DELETE FROM clinics WHERE id = $1
`

func (q *Queries) DeleteClinic(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClinic, id)
	return err
}

const getClinic = `-- name: GetClinic :one
SELECT id, name, slug, address, phone, is_active, created_at, access_expires_at FROM clinics WHERE id = $1
`

func (q *Queries) GetClinic(ctx context.Context, id int64) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinic, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
	)
	return i, err
}

const getClinicBySlug = `-- name: GetClinicBySlug :one
SELECT id, name, slug, address, phone, is_active, created_at, access_expires_at FROM clinics WHERE lower(slug) = lower($1)
`

func (q *Queries) GetClinicBySlug(ctx context.Context, lower string) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinicBySlug, lower)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
	)
	return i, err
}

const listActiveClinics = `-- name: ListActiveClinics :many
SELECT id, name, slug FROM clinics WHERE is_active = true ORDER BY name
`

type ListActiveClinicsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Public list used by the login clinic picker (only non-sensitive fields).
func (q *Queries) ListActiveClinics(ctx context.Context) ([]ListActiveClinicsRow, error) {
	rows, err := q.db.Query(ctx, listActiveClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveClinicsRow{}
	for rows.Next() {
		var i ListActiveClinicsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClinics = `-- name: ListClinics :many
SELECT c.id, c.name, c.slug, c.address, c.phone, c.is_active, c.created_at, c.access_expires_at,
       (SELECT count(*) FROM users u    WHERE u.clinic_id = c.id AND u.role = 'owner')::bigint AS owner_count,
       (SELECT count(*) FROM patients p WHERE p.clinic_id = c.id)::bigint AS patient_count,
       (SELECT count(*) FROM doctors d  WHERE d.clinic_id = c.id)::bigint AS doctor_count
FROM clinics c
ORDER BY c.created_at DESC
`

type ListClinicsRow struct {
	ID              int64       `json:"id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	Address         pgtype.Text `json:"address"`
	Phone           pgtype.Text `json:"phone"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	AccessExpiresAt *time.Time  `json:"access_expires_at"`
	OwnerCount      int64       `json:"owner_count"`
	PatientCount    int64       `json:"patient_count"`
	DoctorCount     int64       `json:"doctor_count"`
}

// All clinics with quick aggregate counts, for the platform admin panel.
func (q *Queries) ListClinics(ctx context.Context) ([]ListClinicsRow, error) {
	rows, err := q.db.Query(ctx, listClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClinicsRow{}
	for rows.Next() {
		var i ListClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.AccessExpiresAt,
			&i.OwnerCount,
			&i.PatientCount,
			&i.DoctorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClinicAccess = `-- name: SetClinicAccess :one
UPDATE clinics SET access_expires_at = $2 WHERE id = $1 RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at
`

type SetClinicAccessParams struct {
	ID              int64      `json:"id"`
	AccessExpiresAt *time.Time `json:"access_expires_at"`
}

// Срок доступа: NULL — бессрочно, прошлое — заморожена.
func (q *Queries) SetClinicAccess(ctx context.Context, arg SetClinicAccessParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, setClinicAccess, arg.ID, arg.AccessExpiresAt)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
	)
	return i, err
}

const updateClinic = `-- name: UpdateClinic :one
UPDATE clinics SET name = $2, slug = $3, address = $4, phone = $5, is_active = $6
WHERE id = $1
RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at
`

type UpdateClinicParams struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateClinic(ctx context.Context, arg UpdateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, updateClinic,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.Phone,
		arg.IsActive,
	)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
	)
	return i, err
}
