// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clinics.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClinic = `-- name: CreateClinic :one
INSERT INTO clinics (name, slug, address, phone, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token
`

type CreateClinicParams struct {
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, createClinic,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.Phone,
		arg.IsActive,
	)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}

const deleteClinic = `-- name: DeleteClinic :exec
DELETE FROM clinics WHERE id = $1
`

func (q *Queries) DeleteClinic(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClinic, id)
	return err
}

const getClinic = `-- name: GetClinic :one
SELECT id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token FROM clinics WHERE id = $1
`

func (q *Queries) GetClinic(ctx context.Context, id int64) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinic, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}

const getClinicBySlug = `-- name: GetClinicBySlug :one
SELECT id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token FROM clinics WHERE lower(slug) = lower($1)
`

func (q *Queries) GetClinicBySlug(ctx context.Context, lower string) (Clinic, error) {
	row := q.db.QueryRow(ctx, getClinicBySlug, lower)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}

const listClinics = `-- name: ListClinics :many
SELECT c.id, c.name, c.slug, c.address, c.phone, c.is_active, c.created_at, c.access_expires_at, c.map_url, c.online_booking, c.greenapi_instance, c.greenapi_token,
       (SELECT count(*) FROM users u    WHERE u.clinic_id = c.id AND u.role = 'owner')::bigint AS owner_count,
       (SELECT count(*) FROM patients p WHERE p.clinic_id = c.id)::bigint AS patient_count,
       (SELECT count(*) FROM doctors d  WHERE d.clinic_id = c.id)::bigint AS doctor_count
FROM clinics c
ORDER BY c.created_at DESC
`

type ListClinicsRow struct {
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	Address          pgtype.Text `json:"address"`
	Phone            pgtype.Text `json:"phone"`
	IsActive         bool        `json:"is_active"`
	CreatedAt        time.Time   `json:"created_at"`
	AccessExpiresAt  *time.Time  `json:"access_expires_at"`
	MapUrl           pgtype.Text `json:"map_url"`
	OnlineBooking    bool        `json:"online_booking"`
	GreenapiInstance pgtype.Text `json:"greenapi_instance"`
	GreenapiToken    pgtype.Text `json:"greenapi_token"`
	OwnerCount       int64       `json:"owner_count"`
	PatientCount     int64       `json:"patient_count"`
	DoctorCount      int64       `json:"doctor_count"`
}

// All clinics with quick aggregate counts, for the platform admin panel.
func (q *Queries) ListClinics(ctx context.Context) ([]ListClinicsRow, error) {
	rows, err := q.db.Query(ctx, listClinics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClinicsRow{}
	for rows.Next() {
		var i ListClinicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.AccessExpiresAt,
			&i.MapUrl,
			&i.OnlineBooking,
			&i.GreenapiInstance,
			&i.GreenapiToken,
			&i.OwnerCount,
			&i.PatientCount,
			&i.DoctorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClinicAccess = `-- name: SetClinicAccess :one
UPDATE clinics SET access_expires_at = $2 WHERE id = $1 RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token
`

type SetClinicAccessParams struct {
	ID              int64      `json:"id"`
	AccessExpiresAt *time.Time `json:"access_expires_at"`
}

// Срок доступа: NULL — бессрочно, прошлое — заморожена.
func (q *Queries) SetClinicAccess(ctx context.Context, arg SetClinicAccessParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, setClinicAccess, arg.ID, arg.AccessExpiresAt)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}

const updateClinic = `-- name: UpdateClinic :one
UPDATE clinics
SET name = $2, slug = $3, address = $4, phone = $5, is_active = $6,
    map_url = $7, online_booking = $8
WHERE id = $1
RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token
`

type UpdateClinicParams struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Slug          string      `json:"slug"`
	Address       pgtype.Text `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	IsActive      bool        `json:"is_active"`
	MapUrl        pgtype.Text `json:"map_url"`
	OnlineBooking bool        `json:"online_booking"`
}

func (q *Queries) UpdateClinic(ctx context.Context, arg UpdateClinicParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, updateClinic,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.Phone,
		arg.IsActive,
		arg.MapUrl,
		arg.OnlineBooking,
	)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}

const updateClinicBookingSettings = `-- name: UpdateClinicBookingSettings :one
UPDATE clinics SET map_url = $2, online_booking = $3
WHERE id = $1
RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token
`

type UpdateClinicBookingSettingsParams struct {
	ID            int64       `json:"id"`
	MapUrl        pgtype.Text `json:"map_url"`
	OnlineBooking bool        `json:"online_booking"`
}

// Настройки онлайн-записи, которые правит сам владелец клиники.
func (q *Queries) UpdateClinicBookingSettings(ctx context.Context, arg UpdateClinicBookingSettingsParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, updateClinicBookingSettings, arg.ID, arg.MapUrl, arg.OnlineBooking)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}

const updateClinicGreenAPI = `-- name: UpdateClinicGreenAPI :one
UPDATE clinics SET greenapi_instance = $2, greenapi_token = $3
WHERE id = $1
RETURNING id, name, slug, address, phone, is_active, created_at, access_expires_at, map_url, online_booking, greenapi_instance, greenapi_token
`

type UpdateClinicGreenAPIParams struct {
	ID               int64       `json:"id"`
	GreenapiInstance pgtype.Text `json:"greenapi_instance"`
	GreenapiToken    pgtype.Text `json:"greenapi_token"`
}

func (q *Queries) UpdateClinicGreenAPI(ctx context.Context, arg UpdateClinicGreenAPIParams) (Clinic, error) {
	row := q.db.QueryRow(ctx, updateClinicGreenAPI, arg.ID, arg.GreenapiInstance, arg.GreenapiToken)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.MapUrl,
		&i.OnlineBooking,
		&i.GreenapiInstance,
		&i.GreenapiToken,
	)
	return i, err
}
