// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (full_name, specialization, phone, color, is_active, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, specialization, phone, color, is_active, created_at, user_id
`

type CreateDoctorParams struct {
	FullName       string      `json:"full_name"`
	Specialization pgtype.Text `json:"specialization"`
	Phone          pgtype.Text `json:"phone"`
	Color          string      `json:"color"`
	IsActive       bool        `json:"is_active"`
	UserID         pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, createDoctor,
		arg.FullName,
		arg.Specialization,
		arg.Phone,
		arg.Color,
		arg.IsActive,
		arg.UserID,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createDoctorSchedule = `-- name: CreateDoctorSchedule :one
INSERT INTO doctor_schedules (doctor_id, weekday, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, doctor_id, weekday, start_time, end_time
`

type CreateDoctorScheduleParams struct {
	DoctorID  int64  `json:"doctor_id"`
	Weekday   int16  `json:"weekday"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

func (q *Queries) CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error) {
	row := q.db.QueryRow(ctx, createDoctorSchedule,
		arg.DoctorID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i DoctorSchedule
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM doctors WHERE id = $1
`

func (q *Queries) DeleteDoctor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDoctor, id)
	return err
}

const deleteDoctorSchedules = `-- name: DeleteDoctorSchedules :exec
DELETE FROM doctor_schedules WHERE doctor_id = $1
`

func (q *Queries) DeleteDoctorSchedules(ctx context.Context, doctorID int64) error {
	_, err := q.db.Exec(ctx, deleteDoctorSchedules, doctorID)
	return err
}

const getDoctor = `-- name: GetDoctor :one
SELECT id, full_name, specialization, phone, color, is_active, created_at, user_id FROM doctors WHERE id = $1
`

func (q *Queries) GetDoctor(ctx context.Context, id int64) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctor, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getDoctorByUserID = `-- name: GetDoctorByUserID :one
SELECT id, full_name, specialization, phone, color, is_active, created_at, user_id FROM doctors WHERE user_id = $1
`

func (q *Queries) GetDoctorByUserID(ctx context.Context, userID pgtype.Int8) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorByUserID, userID)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const listActiveDoctors = `-- name: ListActiveDoctors :many
SELECT id, full_name, specialization, phone, color, is_active, created_at, user_id FROM doctors WHERE is_active = true ORDER BY full_name
`

func (q *Queries) ListActiveDoctors(ctx context.Context) ([]Doctor, error) {
	rows, err := q.db.Query(ctx, listActiveDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Doctor{}
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Specialization,
			&i.Phone,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlinkedDoctorUsers = `-- name: ListUnlinkedDoctorUsers :many
SELECT u.id, u.full_name, u.email
FROM users u
WHERE u.role = 'doctor'
  AND NOT EXISTS (
    SELECT 1 FROM doctors d WHERE d.user_id = u.id AND d.id != $1::bigint
  )
ORDER BY u.full_name
`

type ListUnlinkedDoctorUsersRow struct {
	ID       int64  `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}

func (q *Queries) ListUnlinkedDoctorUsers(ctx context.Context, excludeDoctorID int64) ([]ListUnlinkedDoctorUsersRow, error) {
	rows, err := q.db.Query(ctx, listUnlinkedDoctorUsers, excludeDoctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnlinkedDoctorUsersRow{}
	for rows.Next() {
		var i ListUnlinkedDoctorUsersRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctorSchedules = `-- name: ListDoctorSchedules :many
SELECT id, doctor_id, weekday, start_time, end_time FROM doctor_schedules WHERE doctor_id = $1 ORDER BY weekday, start_time
`

func (q *Queries) ListDoctorSchedules(ctx context.Context, doctorID int64) ([]DoctorSchedule, error) {
	rows, err := q.db.Query(ctx, listDoctorSchedules, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorSchedule{}
	for rows.Next() {
		var i DoctorSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctors = `-- name: ListDoctors :many
SELECT id, full_name, specialization, phone, color, is_active, created_at, user_id FROM doctors ORDER BY full_name
`

func (q *Queries) ListDoctors(ctx context.Context) ([]Doctor, error) {
	rows, err := q.db.Query(ctx, listDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Doctor{}
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Specialization,
			&i.Phone,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctor = `-- name: UpdateDoctor :one
UPDATE doctors
SET full_name = $2, specialization = $3, phone = $4, color = $5, is_active = $6, user_id = $7
WHERE id = $1
RETURNING id, full_name, specialization, phone, color, is_active, created_at, user_id
`

type UpdateDoctorParams struct {
	ID             int64       `json:"id"`
	FullName       string      `json:"full_name"`
	Specialization pgtype.Text `json:"specialization"`
	Phone          pgtype.Text `json:"phone"`
	Color          string      `json:"color"`
	IsActive       bool        `json:"is_active"`
	UserID         pgtype.Int8 `json:"user_id"`
}

func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, updateDoctor,
		arg.ID,
		arg.FullName,
		arg.Specialization,
		arg.Phone,
		arg.Color,
		arg.IsActive,
		arg.UserID,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
