// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doctors.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (clinic_id, full_name, specialization, phone, color, is_active, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, full_name, specialization, phone, color, is_active, created_at, user_id, clinic_id, avatar_path, birth_date, experience_years, bio, skills, education
`

type CreateDoctorParams struct {
	ClinicID       int64       `json:"clinic_id"`
	FullName       string      `json:"full_name"`
	Specialization pgtype.Text `json:"specialization"`
	Phone          pgtype.Text `json:"phone"`
	Color          string      `json:"color"`
	IsActive       bool        `json:"is_active"`
	UserID         pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, createDoctor,
		arg.ClinicID,
		arg.FullName,
		arg.Specialization,
		arg.Phone,
		arg.Color,
		arg.IsActive,
		arg.UserID,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
		&i.ClinicID,
		&i.AvatarPath,
		&i.BirthDate,
		&i.ExperienceYears,
		&i.Bio,
		&i.Skills,
		&i.Education,
	)
	return i, err
}

const createDoctorSchedule = `-- name: CreateDoctorSchedule :one
INSERT INTO doctor_schedules (doctor_id, weekday, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, doctor_id, weekday, start_time, end_time
`

type CreateDoctorScheduleParams struct {
	DoctorID  int64  `json:"doctor_id"`
	Weekday   int16  `json:"weekday"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

func (q *Queries) CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error) {
	row := q.db.QueryRow(ctx, createDoctorSchedule,
		arg.DoctorID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i DoctorSchedule
	err := row.Scan(
		&i.ID,
		&i.DoctorID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM doctors WHERE id = $1 AND clinic_id = $2
`

type DeleteDoctorParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) DeleteDoctor(ctx context.Context, arg DeleteDoctorParams) error {
	_, err := q.db.Exec(ctx, deleteDoctor, arg.ID, arg.ClinicID)
	return err
}

const deleteDoctorSchedules = `-- name: DeleteDoctorSchedules :exec
DELETE FROM doctor_schedules WHERE doctor_id = $1
`

func (q *Queries) DeleteDoctorSchedules(ctx context.Context, doctorID int64) error {
	_, err := q.db.Exec(ctx, deleteDoctorSchedules, doctorID)
	return err
}

const doctorColorTaken = `-- name: DoctorColorTaken :one
SELECT EXISTS(
    SELECT 1 FROM doctors WHERE clinic_id = $1 AND color = $2 AND id <> $3
) AS taken
`

type DoctorColorTakenParams struct {
	ClinicID int64  `json:"clinic_id"`
	Color    string `json:"color"`
	ID       int64  `json:"id"`
}

// Whether another doctor of the clinic already uses this calendar colour
// (colours are unique per clinic so doctors are distinguishable at a glance).
func (q *Queries) DoctorColorTaken(ctx context.Context, arg DoctorColorTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, doctorColorTaken, arg.ClinicID, arg.Color, arg.ID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const doctorUserInClinic = `-- name: DoctorUserInClinic :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE id = $1 AND clinic_id = $2 AND role = 'doctor'
) AS ok
`

type DoctorUserInClinicParams struct {
	ID       int64       `json:"id"`
	ClinicID pgtype.Int8 `json:"clinic_id"`
}

// Whether the given user is a doctor-role account belonging to the clinic. Used
// to validate the user_id a doctor profile is linked to.
func (q *Queries) DoctorUserInClinic(ctx context.Context, arg DoctorUserInClinicParams) (bool, error) {
	row := q.db.QueryRow(ctx, doctorUserInClinic, arg.ID, arg.ClinicID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const getDoctor = `-- name: GetDoctor :one
SELECT id, full_name, specialization, phone, color, is_active, created_at, user_id, clinic_id, avatar_path, birth_date, experience_years, bio, skills, education FROM doctors WHERE id = $1 AND clinic_id = $2
`

type GetDoctorParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) GetDoctor(ctx context.Context, arg GetDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctor, arg.ID, arg.ClinicID)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
		&i.ClinicID,
		&i.AvatarPath,
		&i.BirthDate,
		&i.ExperienceYears,
		&i.Bio,
		&i.Skills,
		&i.Education,
	)
	return i, err
}

const getDoctorByUserID = `-- name: GetDoctorByUserID :one
SELECT id, full_name, specialization, phone, color, is_active, created_at, user_id, clinic_id, avatar_path, birth_date, experience_years, bio, skills, education FROM doctors WHERE user_id = $1 AND clinic_id = $2
`

type GetDoctorByUserIDParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	ClinicID int64       `json:"clinic_id"`
}

// Clinic-scoped so a user can only ever resolve to a doctor profile in their
// own clinic (prevents cross-clinic linkage from leaking a foreign profile).
func (q *Queries) GetDoctorByUserID(ctx context.Context, arg GetDoctorByUserIDParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorByUserID, arg.UserID, arg.ClinicID)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
		&i.ClinicID,
		&i.AvatarPath,
		&i.BirthDate,
		&i.ExperienceYears,
		&i.Bio,
		&i.Skills,
		&i.Education,
	)
	return i, err
}

const getDoctorRating = `-- name: GetDoctorRating :one
SELECT COALESCE(ROUND(AVG(rating)::numeric, 1), 0)::float8 AS rating_avg,
       count(rating)::bigint                               AS rating_count
FROM appointments
WHERE doctor_id = $1 AND rating IS NOT NULL AND status <> 'cancelled'
`

type GetDoctorRatingRow struct {
	RatingAvg   float64 `json:"rating_avg"`
	RatingCount int64   `json:"rating_count"`
}

// Средняя оценка врача для его личного кабинета (/doctors/me).
func (q *Queries) GetDoctorRating(ctx context.Context, doctorID int64) (GetDoctorRatingRow, error) {
	row := q.db.QueryRow(ctx, getDoctorRating, doctorID)
	var i GetDoctorRatingRow
	err := row.Scan(&i.RatingAvg, &i.RatingCount)
	return i, err
}

const listDoctorSchedules = `-- name: ListDoctorSchedules :many
SELECT s.id, s.doctor_id, s.weekday, s.start_time, s.end_time FROM doctor_schedules s
JOIN doctors d ON d.id = s.doctor_id
WHERE s.doctor_id = $1 AND d.clinic_id = $2
ORDER BY s.weekday, s.start_time
`

type ListDoctorSchedulesParams struct {
	DoctorID int64 `json:"doctor_id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) ListDoctorSchedules(ctx context.Context, arg ListDoctorSchedulesParams) ([]DoctorSchedule, error) {
	rows, err := q.db.Query(ctx, listDoctorSchedules, arg.DoctorID, arg.ClinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoctorSchedule{}
	for rows.Next() {
		var i DoctorSchedule
		if err := rows.Scan(
			&i.ID,
			&i.DoctorID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoctors = `-- name: ListDoctors :many
SELECT d.id, d.full_name, d.specialization, d.phone, d.color, d.is_active, d.created_at, d.user_id, d.clinic_id, d.avatar_path, d.birth_date, d.experience_years, d.bio, d.skills, d.education, COALESCE(u.email, '') AS user_email,
    (SELECT COALESCE(ROUND(AVG(a.rating)::numeric, 1), 0)::float8
       FROM appointments a
      WHERE a.doctor_id = d.id AND a.rating IS NOT NULL
        AND a.status <> 'cancelled')           AS rating_avg,
    (SELECT count(*)
       FROM appointments a
      WHERE a.doctor_id = d.id AND a.rating IS NOT NULL
        AND a.status <> 'cancelled')::bigint   AS rating_count
FROM doctors d
LEFT JOIN users u ON u.id = d.user_id
WHERE d.clinic_id = $1
ORDER BY d.full_name
`

type ListDoctorsRow struct {
	ID              int64       `json:"id"`
	FullName        string      `json:"full_name"`
	Specialization  pgtype.Text `json:"specialization"`
	Phone           pgtype.Text `json:"phone"`
	Color           string      `json:"color"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	UserID          pgtype.Int8 `json:"user_id"`
	ClinicID        int64       `json:"clinic_id"`
	AvatarPath      pgtype.Text `json:"avatar_path"`
	BirthDate       *time.Time  `json:"birth_date"`
	ExperienceYears int32       `json:"experience_years"`
	Bio             pgtype.Text `json:"bio"`
	Skills          pgtype.Text `json:"skills"`
	Education       pgtype.Text `json:"education"`
	UserEmail       string      `json:"user_email"`
	RatingAvg       float64     `json:"rating_avg"`
	RatingCount     int64       `json:"rating_count"`
}

// Includes the linked account's login (email) so the admin panel can show it,
// plus the doctor's average visit rating (1–10, from completed appointments;
// appointments of a doctor are always in the doctor's clinic by construction).
func (q *Queries) ListDoctors(ctx context.Context, clinicID int64) ([]ListDoctorsRow, error) {
	rows, err := q.db.Query(ctx, listDoctors, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoctorsRow{}
	for rows.Next() {
		var i ListDoctorsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Specialization,
			&i.Phone,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UserID,
			&i.ClinicID,
			&i.AvatarPath,
			&i.BirthDate,
			&i.ExperienceYears,
			&i.Bio,
			&i.Skills,
			&i.Education,
			&i.UserEmail,
			&i.RatingAvg,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlinkedDoctorUsers = `-- name: ListUnlinkedDoctorUsers :many
SELECT u.id, u.full_name, u.email
FROM users u
WHERE u.clinic_id = $1
  AND u.role = 'doctor'
  AND NOT EXISTS (
    SELECT 1 FROM doctors d WHERE d.user_id = u.id AND d.id != $2::bigint
  )
ORDER BY u.full_name
`

type ListUnlinkedDoctorUsersParams struct {
	ClinicID        pgtype.Int8 `json:"clinic_id"`
	ExcludeDoctorID int64       `json:"exclude_doctor_id"`
}

type ListUnlinkedDoctorUsersRow struct {
	ID       int64  `json:"id"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}

// Clinic users with the "doctor" role not yet linked to a doctor profile
// (or linked to the given doctor, so editing keeps showing its own link).
func (q *Queries) ListUnlinkedDoctorUsers(ctx context.Context, arg ListUnlinkedDoctorUsersParams) ([]ListUnlinkedDoctorUsersRow, error) {
	rows, err := q.db.Query(ctx, listUnlinkedDoctorUsers, arg.ClinicID, arg.ExcludeDoctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnlinkedDoctorUsersRow{}
	for rows.Next() {
		var i ListUnlinkedDoctorUsersRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctor = `-- name: UpdateDoctor :one
UPDATE doctors
SET full_name = $2, specialization = $3, phone = $4, color = $5, is_active = $6, user_id = $7
WHERE id = $1 AND clinic_id = $8
RETURNING id, full_name, specialization, phone, color, is_active, created_at, user_id, clinic_id, avatar_path, birth_date, experience_years, bio, skills, education
`

type UpdateDoctorParams struct {
	ID             int64       `json:"id"`
	FullName       string      `json:"full_name"`
	Specialization pgtype.Text `json:"specialization"`
	Phone          pgtype.Text `json:"phone"`
	Color          string      `json:"color"`
	IsActive       bool        `json:"is_active"`
	UserID         pgtype.Int8 `json:"user_id"`
	ClinicID       int64       `json:"clinic_id"`
}

// Административные поля. Профильные (стаж, опыт, навыки) врач ведёт сам —
// см. UpdateDoctorProfile, чтобы правки владельца и врача не затирали друг друга.
func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, updateDoctor,
		arg.ID,
		arg.FullName,
		arg.Specialization,
		arg.Phone,
		arg.Color,
		arg.IsActive,
		arg.UserID,
		arg.ClinicID,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
		&i.ClinicID,
		&i.AvatarPath,
		&i.BirthDate,
		&i.ExperienceYears,
		&i.Bio,
		&i.Skills,
		&i.Education,
	)
	return i, err
}

const updateDoctorAvatar = `-- name: UpdateDoctorAvatar :one
UPDATE doctors SET avatar_path = $2 WHERE id = $1 AND clinic_id = $3 RETURNING id, full_name, specialization, phone, color, is_active, created_at, user_id, clinic_id, avatar_path, birth_date, experience_years, bio, skills, education
`

type UpdateDoctorAvatarParams struct {
	ID         int64       `json:"id"`
	AvatarPath pgtype.Text `json:"avatar_path"`
	ClinicID   int64       `json:"clinic_id"`
}

func (q *Queries) UpdateDoctorAvatar(ctx context.Context, arg UpdateDoctorAvatarParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, updateDoctorAvatar, arg.ID, arg.AvatarPath, arg.ClinicID)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
		&i.ClinicID,
		&i.AvatarPath,
		&i.BirthDate,
		&i.ExperienceYears,
		&i.Bio,
		&i.Skills,
		&i.Education,
	)
	return i, err
}

const updateDoctorProfile = `-- name: UpdateDoctorProfile :one
UPDATE doctors
SET specialization   = $2,
    phone            = $3,
    birth_date       = $4,
    experience_years = $5,
    bio              = $6,
    skills           = $7,
    education        = $8
WHERE id = $1 AND clinic_id = $9
RETURNING id, full_name, specialization, phone, color, is_active, created_at, user_id, clinic_id, avatar_path, birth_date, experience_years, bio, skills, education
`

type UpdateDoctorProfileParams struct {
	ID              int64       `json:"id"`
	Specialization  pgtype.Text `json:"specialization"`
	Phone           pgtype.Text `json:"phone"`
	BirthDate       *time.Time  `json:"birth_date"`
	ExperienceYears int32       `json:"experience_years"`
	Bio             pgtype.Text `json:"bio"`
	Skills          pgtype.Text `json:"skills"`
	Education       pgtype.Text `json:"education"`
	ClinicID        int64       `json:"clinic_id"`
}

// Профиль врача: его он редактирует в личном кабинете (владелец — тоже, из
// карточки врача). Цвет, активность и привязку к учётке здесь не трогаем.
func (q *Queries) UpdateDoctorProfile(ctx context.Context, arg UpdateDoctorProfileParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, updateDoctorProfile,
		arg.ID,
		arg.Specialization,
		arg.Phone,
		arg.BirthDate,
		arg.ExperienceYears,
		arg.Bio,
		arg.Skills,
		arg.Education,
		arg.ClinicID,
	)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Specialization,
		&i.Phone,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UserID,
		&i.ClinicID,
		&i.AvatarPath,
		&i.BirthDate,
		&i.ExperienceYears,
		&i.Bio,
		&i.Skills,
		&i.Education,
	)
	return i, err
}
