// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (clinic_id, user_id, user_name, action, message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEventParams struct {
	ClinicID int64       `json:"clinic_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	UserName string      `json:"user_name"`
	Action   string      `json:"action"`
	Message  string      `json:"message"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ClinicID,
		arg.UserID,
		arg.UserName,
		arg.Action,
		arg.Message,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, clinic_id, user_id, user_name, action, message, created_at FROM events
WHERE clinic_id = $1
  AND (
    $2::bigint = 0
    OR ($3::text = 'old' AND id > $2::bigint)
    OR ($3::text <> 'old' AND id < $2::bigint)
  )
ORDER BY
    CASE WHEN $3::text = 'old' THEN id END ASC,
    id DESC
LIMIT $4
`

type ListEventsParams struct {
	ClinicID int64  `json:"clinic_id"`
	Cursor   int64  `json:"cursor"`
	Sort     string `json:"sort"`
	PageSize int32  `json:"page_size"`
}

// Курсор по id, а не OFFSET: события пишутся непрерывно, и при листании
// по смещению уже показанные строки уезжали бы вниз и дублировались.
// cursor = 0 — первая страница. При sort=old листаем вперёд по возрастанию id,
// при sort=new (по умолчанию) — назад по убыванию.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.ClinicID,
		arg.Cursor,
		arg.Sort,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.UserID,
			&i.UserName,
			&i.Action,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
