// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID            int64       `json:"id"`
	PatientID     int64       `json:"patient_id"`
	DoctorID      int64       `json:"doctor_id"`
	StartTime     time.Time   `json:"start_time"`
	EndTime       time.Time   `json:"end_time"`
	Status        string      `json:"status"`
	Diagnosis     pgtype.Text `json:"diagnosis"`
	Description   pgtype.Text `json:"description"`
	NextVisitDate *time.Time  `json:"next_visit_date"`
	CreatedBy     pgtype.Int8 `json:"created_by"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	ClinicID      int64       `json:"clinic_id"`
}

type AppointmentService struct {
	ID            int64       `json:"id"`
	AppointmentID int64       `json:"appointment_id"`
	ClinicID      int64       `json:"clinic_id"`
	ServiceID     pgtype.Int8 `json:"service_id"`
	DoctorID      pgtype.Int8 `json:"doctor_id"`
	Name          string      `json:"name"`
	Price         int64       `json:"price"`
	Quantity      int32       `json:"quantity"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Clinic struct {
	ID              int64       `json:"id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	Address         pgtype.Text `json:"address"`
	Phone           pgtype.Text `json:"phone"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	AccessExpiresAt *time.Time  `json:"access_expires_at"`
}

type Doctor struct {
	ID              int64       `json:"id"`
	FullName        string      `json:"full_name"`
	Specialization  pgtype.Text `json:"specialization"`
	Phone           pgtype.Text `json:"phone"`
	Color           string      `json:"color"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	UserID          pgtype.Int8 `json:"user_id"`
	ClinicID        int64       `json:"clinic_id"`
	AvatarPath      pgtype.Text `json:"avatar_path"`
	BirthDate       *time.Time  `json:"birth_date"`
	ExperienceYears int32       `json:"experience_years"`
	Bio             pgtype.Text `json:"bio"`
	Skills          pgtype.Text `json:"skills"`
	Education       pgtype.Text `json:"education"`
}

type DoctorSchedule struct {
	ID        int64  `json:"id"`
	DoctorID  int64  `json:"doctor_id"`
	Weekday   int16  `json:"weekday"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type Event struct {
	ID        int64       `json:"id"`
	ClinicID  int64       `json:"clinic_id"`
	UserID    pgtype.Int8 `json:"user_id"`
	UserName  string      `json:"user_name"`
	Action    string      `json:"action"`
	Message   string      `json:"message"`
	CreatedAt time.Time   `json:"created_at"`
}

type Patient struct {
	ID        int64       `json:"id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
	CreatedAt time.Time   `json:"created_at"`
	// клиника, заведшая карточку; сама карточка общая для платформы
	ClinicID   int64       `json:"clinic_id"`
	Iin        pgtype.Text `json:"iin"`
	Gender     pgtype.Text `json:"gender"`
	AvatarPath pgtype.Text `json:"avatar_path"`
}

type PatientRecord struct {
	ID        int64       `json:"id"`
	PatientID int64       `json:"patient_id"`
	Type      string      `json:"type"`
	Title     pgtype.Text `json:"title"`
	Note      pgtype.Text `json:"note"`
	FilePath  pgtype.Text `json:"file_path"`
	FileName  pgtype.Text `json:"file_name"`
	CreatedBy pgtype.Int8 `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	ClinicID  int64       `json:"clinic_id"`
}

type Service struct {
	ID          int64       `json:"id"`
	ClinicID    int64       `json:"clinic_id"`
	Name        string      `json:"name"`
	Price       int64       `json:"price"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	ID           int64       `json:"id"`
	FullName     string      `json:"full_name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	CreatedAt    time.Time   `json:"created_at"`
	ClinicID     pgtype.Int8 `json:"clinic_id"`
	TokenVersion int32       `json:"token_version"`
}
