// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE notifications
SET status = 'sending'
WHERE id IN (
    SELECT id FROM notifications
    WHERE status = 'queued' AND next_attempt_at <= now()
    ORDER BY id
    LIMIT $1::int
    FOR UPDATE SKIP LOCKED
)
RETURNING id, clinic_id, appointment_id, channel, recipient, text, status, error, attempts, next_attempt_at, created_at, sent_at
`

// Забираем пачку к отправке. SKIP LOCKED — на случай двух воркеров.
func (q *Queries) ClaimNotifications(ctx context.Context, batch int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, claimNotifications, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.AppointmentID,
			&i.Channel,
			&i.Recipient,
			&i.Text,
			&i.Status,
			&i.Error,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (clinic_id, appointment_id, channel, recipient, text)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, clinic_id, appointment_id, channel, recipient, text, status, error, attempts, next_attempt_at, created_at, sent_at
`

type CreateNotificationParams struct {
	ClinicID      int64       `json:"clinic_id"`
	AppointmentID pgtype.Int8 `json:"appointment_id"`
	Channel       string      `json:"channel"`
	Recipient     string      `json:"recipient"`
	Text          string      `json:"text"`
}

// Очередь уведомлений клиентам (outbox). Строка кладётся в той же транзакции,
// что и действие (заявка создана / подтверждена / отклонена), а отправляет её
// фоновый воркер: недоступный WhatsApp не должен ронять работу в CRM.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ClinicID,
		arg.AppointmentID,
		arg.Channel,
		arg.Recipient,
		arg.Text,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.AppointmentID,
		&i.Channel,
		&i.Recipient,
		&i.Text,
		&i.Status,
		&i.Error,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const listNotificationsByAppointment = `-- name: ListNotificationsByAppointment :many
SELECT id, clinic_id, appointment_id, channel, recipient, text, status, error, attempts, next_attempt_at, created_at, sent_at FROM notifications
WHERE appointment_id = $1
ORDER BY id
`

func (q *Queries) ListNotificationsByAppointment(ctx context.Context, appointmentID pgtype.Int8) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByAppointment, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.AppointmentID,
			&i.Channel,
			&i.Recipient,
			&i.Text,
			&i.Status,
			&i.Error,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications
SET attempts = attempts + 1, error = $2, status = 'failed'
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

// Окончательная ошибка (номера нет в WhatsApp) — ретраи бессмысленны.
func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.Error)
	return err
}

const markNotificationRetry = `-- name: MarkNotificationRetry :exec
UPDATE notifications
SET attempts = attempts + 1,
    error = $1::text,
    status = CASE WHEN attempts + 1 >= $2::int THEN 'failed' ELSE 'queued' END,
    next_attempt_at = now() + ($3::int * interval '1 second')
WHERE id = $4
`

type MarkNotificationRetryParams struct {
	Error          string `json:"error"`
	MaxAttempts    int32  `json:"max_attempts"`
	BackoffSeconds int32  `json:"backoff_seconds"`
	ID             int64  `json:"id"`
}

// Неудачная попытка: либо ставим обратно в очередь с задержкой, либо, когда
// попытки кончились, помечаем failed.
func (q *Queries) MarkNotificationRetry(ctx context.Context, arg MarkNotificationRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationRetry,
		arg.Error,
		arg.MaxAttempts,
		arg.BackoffSeconds,
		arg.ID,
	)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET status = 'sent', sent_at = now(), error = NULL
WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const requeueStaleSending = `-- name: RequeueStaleSending :exec
UPDATE notifications
SET status = 'queued'
WHERE status = 'sending' AND next_attempt_at < now() - interval '5 minutes'
`

// Воркер упал посреди отправки: строки, зависшие в sending, возвращаем в очередь.
func (q *Queries) RequeueStaleSending(ctx context.Context) error {
	_, err := q.db.Exec(ctx, requeueStaleSending)
	return err
}
