// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (full_name, phone, birth_date, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, phone, birth_date, notes, created_at
`

type CreatePatientParams struct {
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
		arg.Notes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getPatient = `-- name: GetPatient :one
SELECT id, full_name, phone, birth_date, notes, created_at FROM patients WHERE id = $1
`

func (q *Queries) GetPatient(ctx context.Context, id int64) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, full_name, phone, birth_date, notes, created_at FROM patients
WHERE
    $1::text IS NULL
    OR full_name ILIKE '%' || $1::text || '%'
    OR phone ILIKE '%' || $1::text || '%'
ORDER BY full_name
LIMIT 200
`

func (q *Queries) ListPatients(ctx context.Context, search pgtype.Text) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.BirthDate,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET full_name = $2, phone = $3, birth_date = $4, notes = $5
WHERE id = $1
RETURNING id, full_name, phone, birth_date, notes, created_at
`

type UpdatePatientParams struct {
	ID        int64       `json:"id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
		arg.Notes,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
