// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPatients = `-- name: CountPatients :one
SELECT count(*) FROM patients p
WHERE (
    $1::text IS NULL
    OR (' ' || p.full_name) ILIKE '% ' || $1::text || '%'
    OR p.phone ILIKE $1::text || '%'
    OR p.iin LIKE $1::text || '%'
  )
`

// Тот же фильтр, что и в ListPatients — для счётчика страниц.
func (q *Queries) CountPatients(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countPatients, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (clinic_id, full_name, phone, birth_date, notes, iin, gender)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender, avatar_path
`

type CreatePatientParams struct {
	ClinicID  int64       `json:"clinic_id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
	Iin       pgtype.Text `json:"iin"`
	Gender    pgtype.Text `json:"gender"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.ClinicID,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
		arg.Notes,
		arg.Iin,
		arg.Gender,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
		&i.AvatarPath,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients WHERE id = $1 AND clinic_id = $2
`

type DeletePatientParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

// Только клиника, заведшая карточку: удаление каскадом уносит приёмы всех клиник.
func (q *Queries) DeletePatient(ctx context.Context, arg DeletePatientParams) error {
	_, err := q.db.Exec(ctx, deletePatient, arg.ID, arg.ClinicID)
	return err
}

const getPatient = `-- name: GetPatient :one
SELECT p.id, p.full_name, p.phone, p.birth_date, p.notes, p.created_at, p.clinic_id, p.iin, p.gender, p.avatar_path, c.name AS clinic_name FROM patients p
LEFT JOIN clinics c ON c.id = p.clinic_id
WHERE p.id = $1
`

type GetPatientRow struct {
	ID         int64       `json:"id"`
	FullName   string      `json:"full_name"`
	Phone      pgtype.Text `json:"phone"`
	BirthDate  *time.Time  `json:"birth_date"`
	Notes      pgtype.Text `json:"notes"`
	CreatedAt  time.Time   `json:"created_at"`
	ClinicID   int64       `json:"clinic_id"`
	Iin        pgtype.Text `json:"iin"`
	Gender     pgtype.Text `json:"gender"`
	AvatarPath pgtype.Text `json:"avatar_path"`
	ClinicName pgtype.Text `json:"clinic_name"`
}

func (q *Queries) GetPatient(ctx context.Context, id int64) (GetPatientRow, error) {
	row := q.db.QueryRow(ctx, getPatient, id)
	var i GetPatientRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
		&i.AvatarPath,
		&i.ClinicName,
	)
	return i, err
}

const getPatientByIIN = `-- name: GetPatientByIIN :one
SELECT p.id, p.full_name, p.phone, p.birth_date, p.notes, p.created_at, p.clinic_id, p.iin, p.gender, p.avatar_path, c.name AS clinic_name FROM patients p
LEFT JOIN clinics c ON c.id = p.clinic_id
WHERE p.iin = $1
`

type GetPatientByIINRow struct {
	ID         int64       `json:"id"`
	FullName   string      `json:"full_name"`
	Phone      pgtype.Text `json:"phone"`
	BirthDate  *time.Time  `json:"birth_date"`
	Notes      pgtype.Text `json:"notes"`
	CreatedAt  time.Time   `json:"created_at"`
	ClinicID   int64       `json:"clinic_id"`
	Iin        pgtype.Text `json:"iin"`
	Gender     pgtype.Text `json:"gender"`
	AvatarPath pgtype.Text `json:"avatar_path"`
	ClinicName pgtype.Text `json:"clinic_name"`
}

// Дедупликация по ИИН в масштабах платформы: одна и та же карточка не должна
// заводиться в каждой клинике заново.
func (q *Queries) GetPatientByIIN(ctx context.Context, iin pgtype.Text) (GetPatientByIINRow, error) {
	row := q.db.QueryRow(ctx, getPatientByIIN, iin)
	var i GetPatientByIINRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
		&i.AvatarPath,
		&i.ClinicName,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many

SELECT p.id, p.full_name, p.phone, p.birth_date, p.notes, p.created_at, p.clinic_id, p.iin, p.gender, p.avatar_path, c.name AS clinic_name FROM patients p
LEFT JOIN clinics c ON c.id = p.clinic_id
WHERE (
    $1::text IS NULL
    OR (' ' || p.full_name) ILIKE '% ' || $1::text || '%'
    OR p.phone ILIKE $1::text || '%'
    OR p.iin LIKE $1::text || '%'
  )
ORDER BY p.full_name
LIMIT $3 OFFSET $2
`

type ListPatientsParams struct {
	Search     pgtype.Text `json:"search"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type ListPatientsRow struct {
	ID         int64       `json:"id"`
	FullName   string      `json:"full_name"`
	Phone      pgtype.Text `json:"phone"`
	BirthDate  *time.Time  `json:"birth_date"`
	Notes      pgtype.Text `json:"notes"`
	CreatedAt  time.Time   `json:"created_at"`
	ClinicID   int64       `json:"clinic_id"`
	Iin        pgtype.Text `json:"iin"`
	Gender     pgtype.Text `json:"gender"`
	AvatarPath pgtype.Text `json:"avatar_path"`
	ClinicName pgtype.Text `json:"clinic_name"`
}

// Пациенты — общие для всей платформы: карточку, заведённую одной клиникой,
// видят и могут дополнять остальные. patients.clinic_id — это клиника, которая
// завела карточку; она же единственная, кому разрешено её удалить.
// Matches when the search term is a prefix of any word in the name, a prefix
// of the phone number, or a prefix of the IIN. Ищет по всей платформе.
// Постранично: база общая и растёт, выгружать её целиком нельзя.
func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatientsRow{}
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.BirthDate,
			&i.Notes,
			&i.CreatedAt,
			&i.ClinicID,
			&i.Iin,
			&i.Gender,
			&i.AvatarPath,
			&i.ClinicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET full_name = $2, phone = $3, birth_date = $4, notes = $5, iin = $6, gender = $7
WHERE id = $1
RETURNING id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender, avatar_path
`

type UpdatePatientParams struct {
	ID        int64       `json:"id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
	Iin       pgtype.Text `json:"iin"`
	Gender    pgtype.Text `json:"gender"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
		arg.Notes,
		arg.Iin,
		arg.Gender,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
		&i.AvatarPath,
	)
	return i, err
}

const updatePatientAvatar = `-- name: UpdatePatientAvatar :one
UPDATE patients SET avatar_path = $2 WHERE id = $1 RETURNING id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender, avatar_path
`

type UpdatePatientAvatarParams struct {
	ID         int64       `json:"id"`
	AvatarPath pgtype.Text `json:"avatar_path"`
}

// Карточка общая для платформы, поэтому аватарку может обновить любая клиника.
func (q *Queries) UpdatePatientAvatar(ctx context.Context, arg UpdatePatientAvatarParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatientAvatar, arg.ID, arg.AvatarPath)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
		&i.AvatarPath,
	)
	return i, err
}
