// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (clinic_id, full_name, phone, birth_date, notes, iin, gender)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender
`

type CreatePatientParams struct {
	ClinicID  int64       `json:"clinic_id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
	Iin       pgtype.Text `json:"iin"`
	Gender    pgtype.Text `json:"gender"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.ClinicID,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
		arg.Notes,
		arg.Iin,
		arg.Gender,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
	)
	return i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients WHERE id = $1 AND clinic_id = $2
`

type DeletePatientParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) DeletePatient(ctx context.Context, arg DeletePatientParams) error {
	_, err := q.db.Exec(ctx, deletePatient, arg.ID, arg.ClinicID)
	return err
}

const getPatient = `-- name: GetPatient :one
SELECT id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender FROM patients WHERE id = $1 AND clinic_id = $2
`

type GetPatientParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) GetPatient(ctx context.Context, arg GetPatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, arg.ID, arg.ClinicID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
	)
	return i, err
}

const getPatientByIIN = `-- name: GetPatientByIIN :one
SELECT id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender FROM patients WHERE clinic_id = $1 AND iin = $2
`

type GetPatientByIINParams struct {
	ClinicID int64       `json:"clinic_id"`
	Iin      pgtype.Text `json:"iin"`
}

// Used to de-duplicate patients by ИИН: creating a patient with an existing
// ИИН returns the existing record instead of inserting a duplicate.
func (q *Queries) GetPatientByIIN(ctx context.Context, arg GetPatientByIINParams) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByIIN, arg.ClinicID, arg.Iin)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender FROM patients
WHERE clinic_id = $1
  AND (
    $2::text IS NULL
    OR (' ' || full_name) ILIKE '% ' || $2::text || '%'
    OR phone ILIKE $2::text || '%'
    OR iin LIKE $2::text || '%'
  )
ORDER BY full_name
LIMIT 200
`

type ListPatientsParams struct {
	ClinicID int64       `json:"clinic_id"`
	Search   pgtype.Text `json:"search"`
}

// Matches when the search term is a prefix of any word in the name, a prefix
// of the phone number, or a prefix of the IIN. Scoped to a single clinic.
func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.ClinicID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.BirthDate,
			&i.Notes,
			&i.CreatedAt,
			&i.ClinicID,
			&i.Iin,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsForDoctor = `-- name: ListPatientsForDoctor :many
SELECT DISTINCT p.id, p.full_name, p.phone, p.birth_date, p.notes, p.created_at, p.clinic_id, p.iin, p.gender FROM patients p
JOIN appointments a ON a.patient_id = p.id
WHERE a.doctor_id = $1
  AND p.clinic_id = $2
  AND (
    $3::text IS NULL
    OR (' ' || p.full_name) ILIKE '% ' || $3::text || '%'
    OR p.phone ILIKE $3::text || '%'
    OR p.iin LIKE $3::text || '%'
  )
ORDER BY p.full_name
LIMIT 200
`

type ListPatientsForDoctorParams struct {
	DoctorID int64       `json:"doctor_id"`
	ClinicID int64       `json:"clinic_id"`
	Search   pgtype.Text `json:"search"`
}

// Same prefix-word search, restricted to patients that have at least one
// appointment with the given doctor (within the clinic).
func (q *Queries) ListPatientsForDoctor(ctx context.Context, arg ListPatientsForDoctorParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatientsForDoctor, arg.DoctorID, arg.ClinicID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.BirthDate,
			&i.Notes,
			&i.CreatedAt,
			&i.ClinicID,
			&i.Iin,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patientBelongsToDoctor = `-- name: PatientBelongsToDoctor :one
SELECT EXISTS(
    SELECT 1 FROM appointments WHERE patient_id = $1 AND doctor_id = $2
) AS belongs
`

type PatientBelongsToDoctorParams struct {
	PatientID int64 `json:"patient_id"`
	DoctorID  int64 `json:"doctor_id"`
}

func (q *Queries) PatientBelongsToDoctor(ctx context.Context, arg PatientBelongsToDoctorParams) (bool, error) {
	row := q.db.QueryRow(ctx, patientBelongsToDoctor, arg.PatientID, arg.DoctorID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients
SET full_name = $2, phone = $3, birth_date = $4, notes = $5, iin = $6, gender = $7
WHERE id = $1 AND clinic_id = $8
RETURNING id, full_name, phone, birth_date, notes, created_at, clinic_id, iin, gender
`

type UpdatePatientParams struct {
	ID        int64       `json:"id"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	BirthDate *time.Time  `json:"birth_date"`
	Notes     pgtype.Text `json:"notes"`
	Iin       pgtype.Text `json:"iin"`
	Gender    pgtype.Text `json:"gender"`
	ClinicID  int64       `json:"clinic_id"`
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.BirthDate,
		arg.Notes,
		arg.Iin,
		arg.Gender,
		arg.ClinicID,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.BirthDate,
		&i.Notes,
		&i.CreatedAt,
		&i.ClinicID,
		&i.Iin,
		&i.Gender,
	)
	return i, err
}
