// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAppointmentsInRange(ctx context.Context, arg CountAppointmentsInRangeParams) (int64, error)
	CountArchivedAppointments(ctx context.Context, clinicID int64) (int64, error)
	CountOverlappingAppointments(ctx context.Context, arg CountOverlappingAppointmentsParams) (int64, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error)
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreatePatientRecord(ctx context.Context, arg CreatePatientRecordParams) (PatientRecord, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAppointment(ctx context.Context, arg DeleteAppointmentParams) error
	DeleteArchivedAppointments(ctx context.Context, clinicID int64) error
	DeleteClinic(ctx context.Context, id int64) error
	DeleteClinicUser(ctx context.Context, arg DeleteClinicUserParams) error
	DeleteDoctor(ctx context.Context, arg DeleteDoctorParams) error
	DeleteDoctorSchedules(ctx context.Context, doctorID int64) error
	DeletePatient(ctx context.Context, arg DeletePatientParams) error
	DeletePatientRecord(ctx context.Context, arg DeletePatientRecordParams) error
	// Whether another doctor of the clinic already uses this calendar colour
	// (colours are unique per clinic so doctors are distinguishable at a glance).
	DoctorColorTaken(ctx context.Context, arg DoctorColorTakenParams) (bool, error)
	// Whether the given user is a doctor-role account belonging to the clinic. Used
	// to validate the user_id a doctor profile is linked to.
	DoctorUserInClinic(ctx context.Context, arg DoctorUserInClinicParams) (bool, error)
	GetAppointment(ctx context.Context, arg GetAppointmentParams) (GetAppointmentRow, error)
	GetClinic(ctx context.Context, id int64) (Clinic, error)
	GetClinicBySlug(ctx context.Context, lower string) (Clinic, error)
	// Login within a specific clinic: email is unique per clinic.
	GetClinicUserByEmail(ctx context.Context, arg GetClinicUserByEmailParams) (User, error)
	GetDoctor(ctx context.Context, arg GetDoctorParams) (Doctor, error)
	// Clinic-scoped so a user can only ever resolve to a doctor profile in their
	// own clinic (prevents cross-clinic linkage from leaking a foreign profile).
	GetDoctorByUserID(ctx context.Context, arg GetDoctorByUserIDParams) (Doctor, error)
	GetPatient(ctx context.Context, arg GetPatientParams) (Patient, error)
	// Used to de-duplicate patients by ИИН: creating a patient with an existing
	// ИИН returns the existing record instead of inserting a duplicate.
	GetPatientByIIN(ctx context.Context, arg GetPatientByIINParams) (Patient, error)
	GetPatientRecord(ctx context.Context, arg GetPatientRecordParams) (PatientRecord, error)
	// Platform admin login: superadmins are not attached to any clinic.
	GetSuperadminByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Public list used by the login clinic picker (only non-sensitive fields).
	ListActiveClinics(ctx context.Context) ([]ListActiveClinicsRow, error)
	ListAppointmentsByPatient(ctx context.Context, arg ListAppointmentsByPatientParams) ([]ListAppointmentsByPatientRow, error)
	ListAppointmentsByStatus(ctx context.Context, arg ListAppointmentsByStatusParams) ([]ListAppointmentsByStatusRow, error)
	ListAppointmentsInRange(ctx context.Context, arg ListAppointmentsInRangeParams) ([]ListAppointmentsInRangeRow, error)
	// All clinics with quick aggregate counts, for the platform admin panel.
	ListClinics(ctx context.Context) ([]ListClinicsRow, error)
	ListDoctorSchedules(ctx context.Context, arg ListDoctorSchedulesParams) ([]DoctorSchedule, error)
	// Includes the linked account's login (email) so the admin panel can show it.
	ListDoctors(ctx context.Context, clinicID int64) ([]ListDoctorsRow, error)
	ListPatientRecords(ctx context.Context, arg ListPatientRecordsParams) ([]ListPatientRecordsRow, error)
	// Matches when the search term is a prefix of any word in the name, a prefix
	// of the phone number, or a prefix of the IIN. Scoped to a single clinic.
	ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error)
	// Same prefix-word search, restricted to patients that have at least one
	// appointment with the given doctor (within the clinic).
	ListPatientsForDoctor(ctx context.Context, arg ListPatientsForDoctorParams) ([]Patient, error)
	// Clinic users with the "doctor" role not yet linked to a doctor profile
	// (or linked to the given doctor, so editing keeps showing its own link).
	ListUnlinkedDoctorUsers(ctx context.Context, arg ListUnlinkedDoctorUsersParams) ([]ListUnlinkedDoctorUsersRow, error)
	ListUsersByClinic(ctx context.Context, clinicID pgtype.Int8) ([]ListUsersByClinicRow, error)
	PatientBelongsToDoctor(ctx context.Context, arg PatientBelongsToDoctorParams) (bool, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateClinic(ctx context.Context, arg UpdateClinicParams) (Clinic, error)
	UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	// Bumping token_version invalidates the user's existing access/refresh tokens.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
