// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAppointmentsInRange(ctx context.Context, arg CountAppointmentsInRangeParams) (int64, error)
	CountArchivedAppointments(ctx context.Context) (int64, error)
	CountOverlappingAppointments(ctx context.Context, arg CountOverlappingAppointmentsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAppointment(ctx context.Context, id int64) error
	DeleteArchivedAppointments(ctx context.Context) error
	DeleteDoctor(ctx context.Context, id int64) error
	DeleteDoctorSchedules(ctx context.Context, doctorID int64) error
	DeletePatient(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAppointment(ctx context.Context, id int64) (GetAppointmentRow, error)
	GetDoctor(ctx context.Context, id int64) (Doctor, error)
	GetPatient(ctx context.Context, id int64) (Patient, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListActiveDoctors(ctx context.Context) ([]Doctor, error)
	ListAppointmentsByPatient(ctx context.Context, patientID int64) ([]ListAppointmentsByPatientRow, error)
	ListAppointmentsInRange(ctx context.Context, arg ListAppointmentsInRangeParams) ([]ListAppointmentsInRangeRow, error)
	ListDoctorSchedules(ctx context.Context, doctorID int64) ([]DoctorSchedule, error)
	ListDoctors(ctx context.Context) ([]Doctor, error)
	ListPatients(ctx context.Context, search pgtype.Text) ([]Patient, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
