// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAppointmentsInRange(ctx context.Context, arg CountAppointmentsInRangeParams) (int64, error)
	CountArchivedAppointments(ctx context.Context, clinicID int64) (int64, error)
	// Guards against removing a clinic's last owner (nobody could administer it).
	CountClinicOwners(ctx context.Context, clinicID pgtype.Int8) (int64, error)
	CountOverlappingAppointments(ctx context.Context, arg CountOverlappingAppointmentsParams) (int64, error)
	// Тот же фильтр, что и в ListPatients — для счётчика страниц.
	CountPatients(ctx context.Context, search pgtype.Text) (int64, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAppointmentService(ctx context.Context, arg CreateAppointmentServiceParams) (AppointmentService, error)
	CreateClinic(ctx context.Context, arg CreateClinicParams) (Clinic, error)
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateDoctorSchedule(ctx context.Context, arg CreateDoctorScheduleParams) (DoctorSchedule, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreatePatientRecord(ctx context.Context, arg CreatePatientRecordParams) (PatientRecord, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAppointment(ctx context.Context, arg DeleteAppointmentParams) error
	DeleteAppointmentServices(ctx context.Context, arg DeleteAppointmentServicesParams) error
	DeleteArchivedAppointments(ctx context.Context, clinicID int64) error
	DeleteClinic(ctx context.Context, id int64) error
	DeleteClinicUser(ctx context.Context, arg DeleteClinicUserParams) error
	DeleteDoctor(ctx context.Context, arg DeleteDoctorParams) error
	DeleteDoctorSchedules(ctx context.Context, doctorID int64) error
	// Только клиника, заведшая карточку: удаление каскадом уносит приёмы всех клиник.
	DeletePatient(ctx context.Context, arg DeletePatientParams) error
	DeletePatientRecord(ctx context.Context, arg DeletePatientRecordParams) error
	DeleteService(ctx context.Context, arg DeleteServiceParams) error
	DeleteSuperadmin(ctx context.Context, id int64) error
	// Whether another doctor of the clinic already uses this calendar colour
	// (colours are unique per clinic so doctors are distinguishable at a glance).
	DoctorColorTaken(ctx context.Context, arg DoctorColorTakenParams) (bool, error)
	// Whether the given user is a doctor-role account belonging to the clinic. Used
	// to validate the user_id a doctor profile is linked to.
	DoctorUserInClinic(ctx context.Context, arg DoctorUserInClinicParams) (bool, error)
	GetAppointment(ctx context.Context, arg GetAppointmentParams) (GetAppointmentRow, error)
	GetClinic(ctx context.Context, id int64) (Clinic, error)
	GetClinicBySlug(ctx context.Context, lower string) (Clinic, error)
	// A single clinic user, scoped to their clinic (used by the platform panel to
	// reset a clinic account's password without leaving the clinic boundary).
	GetClinicUser(ctx context.Context, arg GetClinicUserParams) (GetClinicUserRow, error)
	// Login within a specific clinic: email is unique per clinic.
	GetClinicUserByEmail(ctx context.Context, arg GetClinicUserByEmailParams) (User, error)
	GetDoctor(ctx context.Context, arg GetDoctorParams) (Doctor, error)
	// Clinic-scoped so a user can only ever resolve to a doctor profile in their
	// own clinic (prevents cross-clinic linkage from leaking a foreign profile).
	GetDoctorByUserID(ctx context.Context, arg GetDoctorByUserIDParams) (Doctor, error)
	// Средняя оценка врача для его личного кабинета (/doctors/me).
	GetDoctorRating(ctx context.Context, doctorID int64) (GetDoctorRatingRow, error)
	GetPatient(ctx context.Context, id int64) (GetPatientRow, error)
	// Дедупликация по ИИН в масштабах платформы: одна и та же карточка не должна
	// заводиться в каждой клинике заново.
	GetPatientByIIN(ctx context.Context, iin pgtype.Text) (GetPatientByIINRow, error)
	// Файл отдаём любой клинике платформы (медкарта общая).
	GetPatientRecord(ctx context.Context, id int64) (PatientRecord, error)
	GetService(ctx context.Context, arg GetServiceParams) (Service, error)
	// Platform admin login: superadmins are not attached to any clinic.
	GetSuperadminByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Public list used by the login clinic picker (only non-sensitive fields).
	ListActiveClinics(ctx context.Context) ([]ListActiveClinicsRow, error)
	// --- Услуги, оказанные в приёме ---------------------------------------------
	ListAppointmentServices(ctx context.Context, arg ListAppointmentServicesParams) ([]ListAppointmentServicesRow, error)
	// Вся история пациента по всем клиникам платформы. Суммы — только по приёмам
	// клиники-читателя: деньги чужой клиники не показываем.
	ListAppointmentsByPatient(ctx context.Context, arg ListAppointmentsByPatientParams) ([]ListAppointmentsByPatientRow, error)
	ListAppointmentsByStatus(ctx context.Context, arg ListAppointmentsByStatusParams) ([]ListAppointmentsByStatusRow, error)
	// Пациенты общие для платформы, поэтому приём и карточка пациента могут
	// принадлежать разным клиникам — join по patient_id без сверки clinic_id.
	// Врач же всегда из клиники приёма.
	//
	// total везде отдаётся уже со скидкой приёма: сумма чека умножается на
	// (100 - discount_percent) и делится через ROUND (half-up, совпадает с
	// Math.round на фронте). Важно: SUM(bigint) в Postgres — это numeric, поэтому
	// деление здесь точное, а не целочисленное; округляет именно ROUND.
	ListAppointmentsInRange(ctx context.Context, arg ListAppointmentsInRangeParams) ([]ListAppointmentsInRangeRow, error)
	// All clinics with quick aggregate counts, for the platform admin panel.
	ListClinics(ctx context.Context) ([]ListClinicsRow, error)
	ListDoctorSchedules(ctx context.Context, arg ListDoctorSchedulesParams) ([]DoctorSchedule, error)
	// Includes the linked account's login (email) so the admin panel can show it,
	// plus the doctor's average visit rating (1–10, from completed appointments;
	// appointments of a doctor are always in the doctor's clinic by construction).
	ListDoctors(ctx context.Context, clinicID int64) ([]ListDoctorsRow, error)
	// Курсор по id, а не OFFSET: события пишутся непрерывно, и при листании
	// по смещению уже показанные строки уезжали бы вниз и дублировались.
	// before = 0 — первая страница.
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	// Медкарта пациента общая для платформы: снимки и аллергии, заведённые одной
	// клиникой, видит и лечащий врач другой. Название клиники показываем, чтобы
	// было понятно, кто запись сделал; удалять и править можно только свои.
	ListPatientRecords(ctx context.Context, arg ListPatientRecordsParams) ([]ListPatientRecordsRow, error)
	// Пациенты — общие для всей платформы: карточку, заведённую одной клиникой,
	// видят и могут дополнять остальные. patients.clinic_id — это клиника, которая
	// завела карточку; она же единственная, кому разрешено её удалить.
	// Matches when the search term is a prefix of any word in the name, a prefix
	// of the phone number, or a prefix of the IIN. Ищет по всей платформе.
	// Постранично: база общая и растёт, выгружать её целиком нельзя.
	ListPatients(ctx context.Context, arg ListPatientsParams) ([]ListPatientsRow, error)
	// Прайс услуг и оказанные услуги приёма. Всё строго внутри клиники: деньги —
	// единственное, что общая база пациентов не делает публичным.
	// Весь прайс клиники; неактивные тоже, чтобы владелец видел их в справочнике.
	ListServices(ctx context.Context, clinicID int64) ([]Service, error)
	// Platform administrators, for the platform panel's "Администраторы" section.
	ListSuperadmins(ctx context.Context) ([]ListSuperadminsRow, error)
	// Clinic users with the "doctor" role not yet linked to a doctor profile
	// (or linked to the given doctor, so editing keeps showing its own link).
	ListUnlinkedDoctorUsers(ctx context.Context, arg ListUnlinkedDoctorUsersParams) ([]ListUnlinkedDoctorUsersRow, error)
	ListUsersByClinic(ctx context.Context, clinicID pgtype.Int8) ([]ListUsersByClinicRow, error)
	// Выработка врачей. Исполнитель берётся из позиции, а если он не указан — из
	// врача приёма, иначе выработка «потерялась бы».
	RevenueByDoctor(ctx context.Context, arg RevenueByDoctorParams) ([]RevenueByDoctorRow, error)
	// Помесячно за период — для графика «заработок по месяцам».
	RevenueByMonth(ctx context.Context, arg RevenueByMonthParams) ([]RevenueByMonthRow, error)
	// Какие услуги приносят деньги. Группируем по названию-снимку: услуга могла
	// быть переименована или удалена из прайса, а выручка по ней осталась.
	RevenueByService(ctx context.Context, arg RevenueByServiceParams) ([]RevenueByServiceRow, error)
	// Базовый прайс новой клиники — чтобы кассой можно было пользоваться сразу.
	SeedClinicServices(ctx context.Context, clinicID int64) error
	SetAppointmentDiscount(ctx context.Context, arg SetAppointmentDiscountParams) error
	// Оценка посещения 1–10; повторный вызов перезаписывает её.
	SetAppointmentRating(ctx context.Context, arg SetAppointmentRatingParams) error
	// Срок доступа: NULL — бессрочно, прошлое — заморожена.
	SetClinicAccess(ctx context.Context, arg SetClinicAccessParams) (Clinic, error)
	// Сводно по всем клиникам — для панели платформы.
	SumPlatformRevenue(ctx context.Context) (int64, error)
	// --- Статистика выручки ------------------------------------------------------
	// Начислено за период: сумма позиций приёмов, кроме отменённых. Скидка приёма
	// применяется к каждой позиции: сумма умножается на (100 - discount_percent) и
	// делится один раз на группу через ROUND (half-up; SUM(bigint) — это numeric,
	// поэтому округляет именно ROUND, а не деление). Из-за одного округления на
	// группу разные отчёты могут расходиться на единицы тенге.
	SumRevenueInRange(ctx context.Context, arg SumRevenueInRangeParams) (SumRevenueInRangeRow, error)
	UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error)
	UpdateClinic(ctx context.Context, arg UpdateClinicParams) (Clinic, error)
	// Административные поля. Профильные (стаж, опыт, навыки) врач ведёт сам —
	// см. UpdateDoctorProfile, чтобы правки владельца и врача не затирали друг друга.
	UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) (Doctor, error)
	UpdateDoctorAvatar(ctx context.Context, arg UpdateDoctorAvatarParams) (Doctor, error)
	// Профиль врача: его он редактирует в личном кабинете (владелец — тоже, из
	// карточки врача). Цвет, активность и привязку к учётке здесь не трогаем.
	UpdateDoctorProfile(ctx context.Context, arg UpdateDoctorProfileParams) (Doctor, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	// Карточка общая для платформы, поэтому аватарку может обновить любая клиника.
	UpdatePatientAvatar(ctx context.Context, arg UpdatePatientAvatarParams) (Patient, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	// Only name/email; the password goes through UpdateUserPassword.
	UpdateSuperadmin(ctx context.Context, arg UpdateSuperadminParams) (UpdateSuperadminRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	// Bumping token_version invalidates the user's existing access/refresh tokens.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
