// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientRecord = `-- name: CreatePatientRecord :one
INSERT INTO patient_records (patient_id, type, title, note, file_path, file_name, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, patient_id, type, title, note, file_path, file_name, created_by, created_at
`

type CreatePatientRecordParams struct {
	PatientID int64       `json:"patient_id"`
	Type      string      `json:"type"`
	Title     pgtype.Text `json:"title"`
	Note      pgtype.Text `json:"note"`
	FilePath  pgtype.Text `json:"file_path"`
	FileName  pgtype.Text `json:"file_name"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreatePatientRecord(ctx context.Context, arg CreatePatientRecordParams) (PatientRecord, error) {
	row := q.db.QueryRow(ctx, createPatientRecord,
		arg.PatientID,
		arg.Type,
		arg.Title,
		arg.Note,
		arg.FilePath,
		arg.FileName,
		arg.CreatedBy,
	)
	var i PatientRecord
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Type,
		&i.Title,
		&i.Note,
		&i.FilePath,
		&i.FileName,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePatientRecord = `-- name: DeletePatientRecord :exec
DELETE FROM patient_records WHERE id = $1
`

func (q *Queries) DeletePatientRecord(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePatientRecord, id)
	return err
}

const getPatientRecord = `-- name: GetPatientRecord :one
SELECT id, patient_id, type, title, note, file_path, file_name, created_by, created_at FROM patient_records WHERE id = $1
`

func (q *Queries) GetPatientRecord(ctx context.Context, id int64) (PatientRecord, error) {
	row := q.db.QueryRow(ctx, getPatientRecord, id)
	var i PatientRecord
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Type,
		&i.Title,
		&i.Note,
		&i.FilePath,
		&i.FileName,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPatientRecords = `-- name: ListPatientRecords :many
SELECT r.id, r.patient_id, r.type, r.title, r.note, r.file_path, r.file_name,
       r.created_by, r.created_at, COALESCE(u.full_name, '') AS created_by_name
FROM patient_records r
LEFT JOIN users u ON u.id = r.created_by
WHERE r.patient_id = $1
  AND ($2::text IS NULL OR r.type = $2::text)
ORDER BY r.created_at DESC
`

type ListPatientRecordsParams struct {
	PatientID int64       `json:"patient_id"`
	Type      pgtype.Text `json:"type"`
}

type ListPatientRecordsRow struct {
	ID            int64       `json:"id"`
	PatientID     int64       `json:"patient_id"`
	Type          string      `json:"type"`
	Title         pgtype.Text `json:"title"`
	Note          pgtype.Text `json:"note"`
	FilePath      pgtype.Text `json:"file_path"`
	FileName      pgtype.Text `json:"file_name"`
	CreatedBy     pgtype.Int8 `json:"created_by"`
	CreatedAt     time.Time   `json:"created_at"`
	CreatedByName string      `json:"created_by_name"`
}

func (q *Queries) ListPatientRecords(ctx context.Context, arg ListPatientRecordsParams) ([]ListPatientRecordsRow, error) {
	rows, err := q.db.Query(ctx, listPatientRecords, arg.PatientID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPatientRecordsRow{}
	for rows.Next() {
		var i ListPatientRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Type,
			&i.Title,
			&i.Note,
			&i.FilePath,
			&i.FileName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
