// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointmentService = `-- name: CreateAppointmentService :one
INSERT INTO appointment_services (
    appointment_id, clinic_id, service_id, doctor_id, name, price, quantity
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, appointment_id, clinic_id, service_id, doctor_id, name, price, quantity, created_at
`

type CreateAppointmentServiceParams struct {
	AppointmentID int64       `json:"appointment_id"`
	ClinicID      int64       `json:"clinic_id"`
	ServiceID     pgtype.Int8 `json:"service_id"`
	DoctorID      pgtype.Int8 `json:"doctor_id"`
	Name          string      `json:"name"`
	Price         int64       `json:"price"`
	Quantity      int32       `json:"quantity"`
}

func (q *Queries) CreateAppointmentService(ctx context.Context, arg CreateAppointmentServiceParams) (AppointmentService, error) {
	row := q.db.QueryRow(ctx, createAppointmentService,
		arg.AppointmentID,
		arg.ClinicID,
		arg.ServiceID,
		arg.DoctorID,
		arg.Name,
		arg.Price,
		arg.Quantity,
	)
	var i AppointmentService
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.ClinicID,
		&i.ServiceID,
		&i.DoctorID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (clinic_id, name, price, is_active, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, clinic_id, name, price, is_active, created_at, description
`

type CreateServiceParams struct {
	ClinicID    int64       `json:"clinic_id"`
	Name        string      `json:"name"`
	Price       int64       `json:"price"`
	IsActive    bool        `json:"is_active"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ClinicID,
		arg.Name,
		arg.Price,
		arg.IsActive,
		arg.Description,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const deleteAppointmentServices = `-- name: DeleteAppointmentServices :exec
DELETE FROM appointment_services WHERE appointment_id = $1 AND clinic_id = $2
`

type DeleteAppointmentServicesParams struct {
	AppointmentID int64 `json:"appointment_id"`
	ClinicID      int64 `json:"clinic_id"`
}

func (q *Queries) DeleteAppointmentServices(ctx context.Context, arg DeleteAppointmentServicesParams) error {
	_, err := q.db.Exec(ctx, deleteAppointmentServices, arg.AppointmentID, arg.ClinicID)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1 AND clinic_id = $2
`

type DeleteServiceParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.Exec(ctx, deleteService, arg.ID, arg.ClinicID)
	return err
}

const getService = `-- name: GetService :one
SELECT id, clinic_id, name, price, is_active, created_at, description FROM services WHERE id = $1 AND clinic_id = $2
`

type GetServiceParams struct {
	ID       int64 `json:"id"`
	ClinicID int64 `json:"clinic_id"`
}

func (q *Queries) GetService(ctx context.Context, arg GetServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, getService, arg.ID, arg.ClinicID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const listAppointmentServices = `-- name: ListAppointmentServices :many

SELECT s.id, s.appointment_id, s.clinic_id, s.service_id, s.doctor_id, s.name, s.price, s.quantity, s.created_at, d.full_name AS doctor_name
FROM appointment_services s
LEFT JOIN doctors d ON d.id = s.doctor_id
WHERE s.appointment_id = $1 AND s.clinic_id = $2
ORDER BY s.id
`

type ListAppointmentServicesParams struct {
	AppointmentID int64 `json:"appointment_id"`
	ClinicID      int64 `json:"clinic_id"`
}

type ListAppointmentServicesRow struct {
	ID            int64       `json:"id"`
	AppointmentID int64       `json:"appointment_id"`
	ClinicID      int64       `json:"clinic_id"`
	ServiceID     pgtype.Int8 `json:"service_id"`
	DoctorID      pgtype.Int8 `json:"doctor_id"`
	Name          string      `json:"name"`
	Price         int64       `json:"price"`
	Quantity      int32       `json:"quantity"`
	CreatedAt     time.Time   `json:"created_at"`
	DoctorName    pgtype.Text `json:"doctor_name"`
}

// --- Услуги, оказанные в приёме ---------------------------------------------
func (q *Queries) ListAppointmentServices(ctx context.Context, arg ListAppointmentServicesParams) ([]ListAppointmentServicesRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentServices, arg.AppointmentID, arg.ClinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentServicesRow{}
	for rows.Next() {
		var i ListAppointmentServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.ClinicID,
			&i.ServiceID,
			&i.DoctorID,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.DoctorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many

SELECT id, clinic_id, name, price, is_active, created_at, description FROM services WHERE clinic_id = $1 ORDER BY is_active DESC, name
`

// Прайс услуг и оказанные услуги приёма. Всё строго внутри клиники: деньги —
// единственное, что общая база пациентов не делает публичным.
// Весь прайс клиники; неактивные тоже, чтобы владелец видел их в справочнике.
func (q *Queries) ListServices(ctx context.Context, clinicID int64) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, clinicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ClinicID,
			&i.Name,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByDoctor = `-- name: RevenueByDoctor :many
SELECT
    COALESCE(dp.full_name, da.full_name, '')        AS doctor_name,
    COALESCE(SUM(s.quantity), 0)::bigint            AS services_count,
    COALESCE(SUM(s.price * s.quantity), 0)::bigint  AS revenue
FROM appointment_services s
JOIN appointments a ON a.id = s.appointment_id
LEFT JOIN doctors dp ON dp.id = s.doctor_id
LEFT JOIN doctors da ON da.id = a.doctor_id
WHERE s.clinic_id = $1
  AND a.status <> 'cancelled'
  AND a.start_time >= $2
  AND a.start_time <  $3
GROUP BY 1
ORDER BY revenue DESC
LIMIT 20
`

type RevenueByDoctorParams struct {
	ClinicID int64     `json:"clinic_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type RevenueByDoctorRow struct {
	DoctorName    string `json:"doctor_name"`
	ServicesCount int64  `json:"services_count"`
	Revenue       int64  `json:"revenue"`
}

// Выработка врачей. Исполнитель берётся из позиции, а если он не указан — из
// врача приёма, иначе выработка «потерялась бы».
func (q *Queries) RevenueByDoctor(ctx context.Context, arg RevenueByDoctorParams) ([]RevenueByDoctorRow, error) {
	rows, err := q.db.Query(ctx, revenueByDoctor, arg.ClinicID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByDoctorRow{}
	for rows.Next() {
		var i RevenueByDoctorRow
		if err := rows.Scan(&i.DoctorName, &i.ServicesCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByMonth = `-- name: RevenueByMonth :many
SELECT
    to_char(date_trunc('month', a.start_time), 'YYYY-MM')  AS month,
    COALESCE(SUM(s.price * s.quantity), 0)::bigint         AS revenue,
    COALESCE(SUM(s.quantity), 0)::bigint                   AS services_count
FROM appointment_services s
JOIN appointments a ON a.id = s.appointment_id
WHERE s.clinic_id = $1
  AND a.status <> 'cancelled'
  AND a.start_time >= $2
  AND a.start_time <  $3
GROUP BY 1
ORDER BY 1
`

type RevenueByMonthParams struct {
	ClinicID int64     `json:"clinic_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type RevenueByMonthRow struct {
	Month         string `json:"month"`
	Revenue       int64  `json:"revenue"`
	ServicesCount int64  `json:"services_count"`
}

// Помесячно за период — для графика «заработок по месяцам».
func (q *Queries) RevenueByMonth(ctx context.Context, arg RevenueByMonthParams) ([]RevenueByMonthRow, error) {
	rows, err := q.db.Query(ctx, revenueByMonth, arg.ClinicID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByMonthRow{}
	for rows.Next() {
		var i RevenueByMonthRow
		if err := rows.Scan(&i.Month, &i.Revenue, &i.ServicesCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByService = `-- name: RevenueByService :many
SELECT
    s.name                                          AS name,
    COALESCE(SUM(s.quantity), 0)::bigint            AS services_count,
    COALESCE(SUM(s.price * s.quantity), 0)::bigint  AS revenue
FROM appointment_services s
JOIN appointments a ON a.id = s.appointment_id
WHERE s.clinic_id = $1
  AND a.status <> 'cancelled'
  AND a.start_time >= $2
  AND a.start_time <  $3
GROUP BY s.name
ORDER BY revenue DESC
LIMIT 20
`

type RevenueByServiceParams struct {
	ClinicID int64     `json:"clinic_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type RevenueByServiceRow struct {
	Name          string `json:"name"`
	ServicesCount int64  `json:"services_count"`
	Revenue       int64  `json:"revenue"`
}

// Какие услуги приносят деньги. Группируем по названию-снимку: услуга могла
// быть переименована или удалена из прайса, а выручка по ней осталась.
func (q *Queries) RevenueByService(ctx context.Context, arg RevenueByServiceParams) ([]RevenueByServiceRow, error) {
	rows, err := q.db.Query(ctx, revenueByService, arg.ClinicID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByServiceRow{}
	for rows.Next() {
		var i RevenueByServiceRow
		if err := rows.Scan(&i.Name, &i.ServicesCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedClinicServices = `-- name: SeedClinicServices :exec
INSERT INTO services (clinic_id, name, price)
SELECT $1, s.name, s.price
FROM (VALUES
    ('Удаление зуба',   20000::bigint),
    ('Лечение кариеса', 10000::bigint),
    ('Пломба',          10000::bigint)
) AS s(name, price)
ON CONFLICT DO NOTHING
`

// Базовый прайс новой клиники — чтобы кассой можно было пользоваться сразу.
func (q *Queries) SeedClinicServices(ctx context.Context, clinicID int64) error {
	_, err := q.db.Exec(ctx, seedClinicServices, clinicID)
	return err
}

const sumPlatformRevenue = `-- name: SumPlatformRevenue :one
SELECT COALESCE(SUM(s.price * s.quantity), 0)::bigint
FROM appointment_services s
JOIN appointments a ON a.id = s.appointment_id
WHERE a.status <> 'cancelled'
`

// Сводно по всем клиникам — для панели платформы.
func (q *Queries) SumPlatformRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumPlatformRevenue)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumRevenueInRange = `-- name: SumRevenueInRange :one

SELECT
    COALESCE(SUM(s.price * s.quantity), 0)::bigint AS revenue,
    COALESCE(SUM(s.quantity), 0)::bigint           AS services_count,
    count(DISTINCT s.appointment_id)::bigint       AS appointments_count
FROM appointment_services s
JOIN appointments a ON a.id = s.appointment_id
WHERE s.clinic_id = $1
  AND a.status <> 'cancelled'
  AND a.start_time >= $2
  AND a.start_time <  $3
`

type SumRevenueInRangeParams struct {
	ClinicID int64     `json:"clinic_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type SumRevenueInRangeRow struct {
	Revenue           int64 `json:"revenue"`
	ServicesCount     int64 `json:"services_count"`
	AppointmentsCount int64 `json:"appointments_count"`
}

// --- Статистика выручки ------------------------------------------------------
// Начислено за период: сумма позиций приёмов, кроме отменённых.
func (q *Queries) SumRevenueInRange(ctx context.Context, arg SumRevenueInRangeParams) (SumRevenueInRangeRow, error) {
	row := q.db.QueryRow(ctx, sumRevenueInRange, arg.ClinicID, arg.From, arg.To)
	var i SumRevenueInRangeRow
	err := row.Scan(&i.Revenue, &i.ServicesCount, &i.AppointmentsCount)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services SET name = $2, price = $3, is_active = $4, description = $5
WHERE id = $1 AND clinic_id = $6
RETURNING id, clinic_id, name, price, is_active, created_at, description
`

type UpdateServiceParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Price       int64       `json:"price"`
	IsActive    bool        `json:"is_active"`
	Description pgtype.Text `json:"description"`
	ClinicID    int64       `json:"clinic_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.IsActive,
		arg.Description,
		arg.ClinicID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ClinicID,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}
